#!/usr/bin/env bash
set -euo pipefail

# ------------------------------------------------------------
# Paths
# ------------------------------------------------------------

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

TEST_NAME="smoke_test"

SRC="${SCRIPT_DIR}/${TEST_NAME}/smoke.S"
LINKER="${SCRIPT_DIR}/${TEST_NAME}/linker.ld"

ELF="${SCRIPT_DIR}/${TEST_NAME}/smoke.elf"
DUMP="${SCRIPT_DIR}/${TEST_NAME}/smoke.dump"
BIN="${SCRIPT_DIR}/${TEST_NAME}/smoke.bin"

IMEM_MEM="${REPO_ROOT}/zedboard-wrapper/program_imem.mem"

# ------------------------------------------------------------
# Toolchain
# ------------------------------------------------------------
# Override if needed:
#   TOOLCHAIN_PREFIX=riscv32-unknown-elf ./sw/compile.sh
# or:
#   TOOLCHAIN_PREFIX=/path/to/riscv64-unknown-elf ./sw/compile.sh

TOOLCHAIN_PREFIX="${TOOLCHAIN_PREFIX:-riscv64-unknown-elf}"

CC="${TOOLCHAIN_PREFIX}-gcc"
OBJDUMP="${TOOLCHAIN_PREFIX}-objdump"
OBJCOPY="${TOOLCHAIN_PREFIX}-objcopy"
READELF="${TOOLCHAIN_PREFIX}-readelf"

for tool in "${CC}" "${OBJDUMP}" "${OBJCOPY}" "${READELF}"; do
    if ! command -v "${tool}" >/dev/null 2>&1; then
        echo "ERROR: Required tool not found: ${tool}" >&2
        echo "Set TOOLCHAIN_PREFIX, e.g.:" >&2
        echo "  TOOLCHAIN_PREFIX=riscv64-unknown-elf ./sw/compile.sh" >&2
        exit 1
    fi
done

# ------------------------------------------------------------
# Build
# ------------------------------------------------------------

echo "[BUILD] Assembling/linking ${SRC}"

"${CC}" \
    -march=rv32im \
    -mabi=ilp32 \
    -nostdlib \
    -nostartfiles \
    -Wl,--no-relax \
    -Wl,-Map="${SCRIPT_DIR}/${TEST_NAME}/smoke.map" \
    -T "${LINKER}" \
    "${SRC}" \
    -o "${ELF}"

echo "[CHECK] ELF header"
"${READELF}" -h "${ELF}" | grep -E "Class:|Machine:|Entry point"

echo "[DUMP] Writing disassembly to ${DUMP}"

"${OBJDUMP}" \
    -d \
    -M no-aliases,numeric \
    "${ELF}" > "${DUMP}"

# ------------------------------------------------------------
# Create raw binary
# ------------------------------------------------------------
# We convert the ELF to a flat binary and then pack every 4 bytes into
# one 32-bit little-endian word for $readmemh into logic [31:0] mem[].
#
# This is safer than relying directly on objcopy -O verilog, because
# Verilog hex output may be byte-oriented depending on the tool/version,
# while our imem_bram is word-oriented.

echo "[OBJCOPY] Writing raw binary to ${BIN}"

"${OBJCOPY}" \
    -O binary \
    "${ELF}" \
    "${BIN}"

# ------------------------------------------------------------
# Convert binary to 32-bit word .mem
# ------------------------------------------------------------

echo "[MEM] Writing 32-bit word memory image to ${IMEM_MEM}"

python3 - "${BIN}" "${IMEM_MEM}" <<'PY'
import sys
from pathlib import Path

bin_path = Path(sys.argv[1])
mem_path = Path(sys.argv[2])

data = bin_path.read_bytes()

# Pad to 4-byte boundary.
if len(data) % 4 != 0:
    data += bytes(4 - (len(data) % 4))

mem_path.parent.mkdir(parents=True, exist_ok=True)

with mem_path.open("w", encoding="utf-8") as f:
    # f.write("// Auto-generated by sw/compile.sh\n")
    # f.write("// 32-bit little-endian words for imem_bram\n")
    f.write("@00000000\n")

    for i in range(0, len(data), 4):
        word = int.from_bytes(data[i:i+4], byteorder="little")
        f.write(f"{word:08x}\n")

print(f"[MEM] Wrote {len(data) // 4} words")
PY

# ------------------------------------------------------------
# Quick sanity output
# ------------------------------------------------------------

echo
echo "[OK] Build complete"
echo "  ELF : ${ELF}"
echo "  DUMP: ${DUMP}"
echo "  BIN : ${BIN}"
echo "  MEM : ${IMEM_MEM}"
echo
echo "[INFO] First lines of memory image:"
head -n 12 "${IMEM_MEM}"
echo
echo "[INFO] First instructions:"
head -n 30 "${DUMP}"
