#*****************************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# cv32e40p-zedboard-project.tcl: Tcl script for re-creating project 'cv32e40p-zedboard-project'
#
# Generated by Vivado on Fri May 22 13:12:21 EEST 2026
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (cv32e40p-zedboard-project.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "$core_dir/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/clk/rtl/gated_clk_cell.v"
#    "$core_dir/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_ctrl.v"
#    "$core_dir/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_ff1.v"
#    "$core_dir/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_pack_single.v"
#    "$core_dir/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_prepare.v"
#    "$core_dir/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_round_single.v"
#    "$core_dir/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_special.v"
#    "$core_dir/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_srt_single.v"
#    "$core_dir/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_top.v"
#    "$core_dir/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_dp.v"
#    "$core_dir/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_frbus.v"
#    "$core_dir/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_src_type.v"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/cf_math_pkg.sv"
#    "$core_dir/rtl/cv32e40p_aligner.sv"
#    "$core_dir/rtl/include/cv32e40p_pkg.sv"
#    "$core_dir/rtl/cv32e40p_alu.sv"
#    "$core_dir/rtl/cv32e40p_alu_div.sv"
#    "$core_dir/rtl/include/cv32e40p_apu_core_pkg.sv"
#    "$core_dir/rtl/cv32e40p_apu_disp.sv"
#    "$origin_dir/zedboard-wrapper/cv32e40p_clock_gate.sv"
#    "$core_dir/rtl/cv32e40p_compressed_decoder.sv"
#    "$core_dir/rtl/cv32e40p_controller.sv"
#    "$core_dir/rtl/cv32e40p_core.sv"
#    "$core_dir/rtl/cv32e40p_cs_registers.sv"
#    "$core_dir/rtl/include/cv32e40p_fpu_pkg.sv"
#    "$core_dir/rtl/cv32e40p_decoder.sv"
#    "$core_dir/rtl/cv32e40p_ex_stage.sv"
#    "$core_dir/rtl/cv32e40p_ff_one.sv"
#    "$core_dir/rtl/cv32e40p_fifo.sv"
#    "$core_dir/rtl/vendor/pulp_platform_fpnew/src/fpnew_pkg.sv"
#    "$core_dir/rtl/cv32e40p_fp_wrapper.sv"
#    "$core_dir/rtl/cv32e40p_hwloop_regs.sv"
#    "$core_dir/rtl/cv32e40p_id_stage.sv"
#    "$core_dir/rtl/cv32e40p_if_stage.sv"
#    "$core_dir/rtl/cv32e40p_int_controller.sv"
#    "$core_dir/rtl/cv32e40p_load_store_unit.sv"
#    "$core_dir/rtl/cv32e40p_mult.sv"
#    "$core_dir/rtl/cv32e40p_obi_interface.sv"
#    "$core_dir/rtl/cv32e40p_popcnt.sv"
#    "$core_dir/rtl/cv32e40p_prefetch_buffer.sv"
#    "$core_dir/rtl/cv32e40p_prefetch_controller.sv"
#    "$core_dir/rtl/cv32e40p_sleep_unit.sv"
#    "$core_dir/rtl/cv32e40p_top.sv"
#    "$origin_dir/zedboard-wrapper/dmem_bram.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/include/common_cells/registers.svh"
#    "$core_dir/rtl/vendor/pulp_platform_fpnew/src/fpnew_cast_multi.sv"
#    "$core_dir/rtl/vendor/pulp_platform_fpnew/src/fpnew_classifier.sv"
#    "$core_dir/rtl/vendor/pulp_platform_fpnew/src/fpnew_divsqrt_multi.sv"
#    "$core_dir/rtl/vendor/pulp_platform_fpnew/src/fpnew_divsqrt_th_32.sv"
#    "$core_dir/rtl/vendor/pulp_platform_fpnew/src/fpnew_fma.sv"
#    "$core_dir/rtl/vendor/pulp_platform_fpnew/src/fpnew_fma_multi.sv"
#    "$core_dir/rtl/vendor/pulp_platform_fpnew/src/fpnew_noncomp.sv"
#    "$core_dir/rtl/vendor/pulp_platform_fpnew/src/fpnew_opgroup_block.sv"
#    "$core_dir/rtl/vendor/pulp_platform_fpnew/src/fpnew_opgroup_fmt_slice.sv"
#    "$core_dir/rtl/vendor/pulp_platform_fpnew/src/fpnew_opgroup_multifmt_slice.sv"
#    "$core_dir/rtl/vendor/pulp_platform_fpnew/src/fpnew_rounding.sv"
#    "$core_dir/rtl/vendor/pulp_platform_fpnew/src/fpnew_top.sv"
#    "$origin_dir/zedboard-wrapper/imem_bram.sv"
#    "$origin_dir/zedboard-wrapper/program_imem.mem"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/lzc.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/rr_arb_tree.sv"
#    "$origin_dir/zedboard-wrapper/zedboard_cv32e40p_wrapper.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/cb_filter_pkg.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/counter.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/delta_counter.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/sub_per_hash.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/cb_filter.sv"
#    "$core_dir/rtl/cv32e40p_register_file_ff.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/addr_decode.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/binary_to_gray.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/cdc_2phase.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/cdc_fifo_2phase.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/cdc_fifo_gray.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/clk_div.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/deprecated/clock_divider.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/deprecated/clock_divider_counter.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/ecc_pkg.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/ecc_decode.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/ecc_encode.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/edge_detect.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/edge_propagator.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/edge_propagator_rx.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/edge_propagator_tx.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/exp_backoff.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/fall_through_register.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/deprecated/fifo_v1.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/deprecated/fifo_v2.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/fifo_v3.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/deprecated/find_first_one.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/deprecated/generic_LFSR_8bit.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/deprecated/generic_fifo.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/deprecated/generic_fifo_adv.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/gray_to_binary.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/id_queue.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/isochronous_spill_register.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/lfsr.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/lfsr_16bit.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/lfsr_8bit.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/max_counter.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/mv_filter.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/onehot_to_bin.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/plru_tree.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/popcount.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/deprecated/prioarbiter.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/deprecated/pulp_sync.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/deprecated/pulp_sync_wedge.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/deprecated/rrarbiter.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/rstgen.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/rstgen_bypass.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/serial_deglitch.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/shift_reg.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/spill_register.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/deprecated/sram.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/stream_arbiter.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/stream_arbiter_flushable.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/stream_delay.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/stream_demux.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/stream_fifo.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/stream_filter.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/stream_fork.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/stream_fork_dynamic.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/stream_join.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/stream_mux.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/stream_omega_net.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/stream_register.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/stream_to_mem.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/stream_xbar.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/sync.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/sync_wedge.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/unread.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/src/stream_intf.sv"
#    "$core_dir/rtl/vendor/pulp_platform_common_cells/include/common_cells/assertions.svh"
#    "$origin_dir/zedboard-wrapper/constraints.xdc"
#    "$origin_dir/zedboard-wrapper/tb_zedboard_cv32e40p_wrapper.sv"
#
# 3. The following remote source files that were added to the original project:-
#
#    <none>
#
#*****************************************************************************************

# Check file required for this script exists
proc checkRequiredFiles { origin_dir} {
  set status true
  set files [list \
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/clk/rtl/gated_clk_cell.v"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_ctrl.v"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_ff1.v"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_pack_single.v"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_prepare.v"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_round_single.v"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_special.v"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_srt_single.v"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_top.v"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_dp.v"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_frbus.v"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_src_type.v"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/cf_math_pkg.sv"]"\
 "[file normalize "$core_dir/rtl/cv32e40p_aligner.sv"]"\
 "[file normalize "$core_dir/rtl/include/cv32e40p_pkg.sv"]"\
 "[file normalize "$core_dir/rtl/cv32e40p_alu.sv"]"\
 "[file normalize "$core_dir/rtl/cv32e40p_alu_div.sv"]"\
 "[file normalize "$core_dir/rtl/include/cv32e40p_apu_core_pkg.sv"]"\
 "[file normalize "$core_dir/rtl/cv32e40p_apu_disp.sv"]"\
 "[file normalize "$origin_dir/zedboard-wrapper/cv32e40p_clock_gate.sv"]"\
 "[file normalize "$core_dir/rtl/cv32e40p_compressed_decoder.sv"]"\
 "[file normalize "$core_dir/rtl/cv32e40p_controller.sv"]"\
 "[file normalize "$core_dir/rtl/cv32e40p_core.sv"]"\
 "[file normalize "$core_dir/rtl/cv32e40p_cs_registers.sv"]"\
 "[file normalize "$core_dir/rtl/include/cv32e40p_fpu_pkg.sv"]"\
 "[file normalize "$core_dir/rtl/cv32e40p_decoder.sv"]"\
 "[file normalize "$core_dir/rtl/cv32e40p_ex_stage.sv"]"\
 "[file normalize "$core_dir/rtl/cv32e40p_ff_one.sv"]"\
 "[file normalize "$core_dir/rtl/cv32e40p_fifo.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_fpnew/src/fpnew_pkg.sv"]"\
 "[file normalize "$core_dir/rtl/cv32e40p_fp_wrapper.sv"]"\
 "[file normalize "$core_dir/rtl/cv32e40p_hwloop_regs.sv"]"\
 "[file normalize "$core_dir/rtl/cv32e40p_id_stage.sv"]"\
 "[file normalize "$core_dir/rtl/cv32e40p_if_stage.sv"]"\
 "[file normalize "$core_dir/rtl/cv32e40p_int_controller.sv"]"\
 "[file normalize "$core_dir/rtl/cv32e40p_load_store_unit.sv"]"\
 "[file normalize "$core_dir/rtl/cv32e40p_mult.sv"]"\
 "[file normalize "$core_dir/rtl/cv32e40p_obi_interface.sv"]"\
 "[file normalize "$core_dir/rtl/cv32e40p_popcnt.sv"]"\
 "[file normalize "$core_dir/rtl/cv32e40p_prefetch_buffer.sv"]"\
 "[file normalize "$core_dir/rtl/cv32e40p_prefetch_controller.sv"]"\
 "[file normalize "$core_dir/rtl/cv32e40p_sleep_unit.sv"]"\
 "[file normalize "$core_dir/rtl/cv32e40p_top.sv"]"\
 "[file normalize "$origin_dir/zedboard-wrapper/dmem_bram.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/include/common_cells/registers.svh"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_fpnew/src/fpnew_cast_multi.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_fpnew/src/fpnew_classifier.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_fpnew/src/fpnew_divsqrt_multi.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_fpnew/src/fpnew_divsqrt_th_32.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_fpnew/src/fpnew_fma.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_fpnew/src/fpnew_fma_multi.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_fpnew/src/fpnew_noncomp.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_fpnew/src/fpnew_opgroup_block.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_fpnew/src/fpnew_opgroup_fmt_slice.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_fpnew/src/fpnew_opgroup_multifmt_slice.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_fpnew/src/fpnew_rounding.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_fpnew/src/fpnew_top.sv"]"\
 "[file normalize "$origin_dir/zedboard-wrapper/imem_bram.sv"]"\
 "[file normalize "$origin_dir/zedboard-wrapper/program_imem.mem"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/lzc.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/rr_arb_tree.sv"]"\
 "[file normalize "$origin_dir/zedboard-wrapper/zedboard_cv32e40p_wrapper.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/cb_filter_pkg.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/counter.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/delta_counter.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/sub_per_hash.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/cb_filter.sv"]"\
 "[file normalize "$core_dir/rtl/cv32e40p_register_file_ff.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/addr_decode.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/binary_to_gray.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/cdc_2phase.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/cdc_fifo_2phase.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/cdc_fifo_gray.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/clk_div.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/deprecated/clock_divider.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/deprecated/clock_divider_counter.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/ecc_pkg.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/ecc_decode.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/ecc_encode.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/edge_detect.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/edge_propagator.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/edge_propagator_rx.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/edge_propagator_tx.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/exp_backoff.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/fall_through_register.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/deprecated/fifo_v1.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/deprecated/fifo_v2.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/fifo_v3.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/deprecated/find_first_one.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/deprecated/generic_LFSR_8bit.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/deprecated/generic_fifo.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/deprecated/generic_fifo_adv.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/gray_to_binary.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/id_queue.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/isochronous_spill_register.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/lfsr.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/lfsr_16bit.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/lfsr_8bit.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/max_counter.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/mv_filter.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/onehot_to_bin.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/plru_tree.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/popcount.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/deprecated/prioarbiter.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/deprecated/pulp_sync.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/deprecated/pulp_sync_wedge.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/deprecated/rrarbiter.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/rstgen.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/rstgen_bypass.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/serial_deglitch.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/shift_reg.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/spill_register.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/deprecated/sram.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/stream_arbiter.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/stream_arbiter_flushable.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/stream_delay.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/stream_demux.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/stream_fifo.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/stream_filter.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/stream_fork.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/stream_fork_dynamic.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/stream_join.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/stream_mux.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/stream_omega_net.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/stream_register.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/stream_to_mem.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/stream_xbar.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/sync.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/sync_wedge.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/unread.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/src/stream_intf.sv"]"\
 "[file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/include/common_cells/assertions.svh"]"\
 "[file normalize "$origin_dir/zedboard-wrapper/constraints.xdc"]"\
 "[file normalize "$origin_dir/zedboard-wrapper/tb_zedboard_cv32e40p_wrapper.sv"]"\
  ]
  foreach ifile $files {
    if { ![file isfile $ifile] } {
      puts " Could not find local file $ifile "
      set status false
    }
  }

  return $status
}
# Set the reference directory for source file relative paths (by default the value is script directory path)
set script_dir [file dirname [file normalize [info script]]]
set origin_dir [file normalize $script_dir]

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Select which cv32e40p checkout to use. The repository keeps the baseline
# and modified RTL checkouts side by side so the parent repository can stay
# on one branch while Vivado projects choose a design with --experiment or
# --core_dir.
set experiment "baseline"
set core_dir ""
set user_build_dir ""
set clock_period ""

# Set the project name
set _xil_proj_name_ "cv32e40p-zedboard-project"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "cv32e40p-zedboard-project.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--experiment <baseline|no-mul-forwarding>\]"
  puts "$script_file -tclargs \[--core_dir <path-to-cv32e40p-checkout>\]"
  puts "$script_file -tclargs \[--build_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--clock_period <period-ns>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine wrapper/source paths wrt this path. Default"
  puts "                       origin_dir path value is the script directory.\n"
  puts "\[--experiment <name>\]  Select an RTL checkout by experiment name. Defaults"
  puts "                       to baseline. Known values:"
  puts "                         baseline -> cv32e40p_baseline"
  puts "                         no-mul-forwarding -> cv32e40p_no_mul_forwarding\n"
  puts "\[--core_dir <path>\]   Explicit cv32e40p checkout path. Overrides"
  puts "                       --experiment-based selection.\n"
  puts "\[--build_dir <path>\]  Vivado project output directory. Default:"
  puts "                       build/vivado-<experiment>.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--clock_period <ns>\] Override clk_i target period in ns. Default:"
  puts "                       15.000 for baseline, 10.000 for no-mul-forwarding.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--experiment"   { incr i; set experiment [lindex $::argv $i] }
      "--core_dir"     { incr i; set core_dir [lindex $::argv $i] }
      "--build_dir"    { incr i; set user_build_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--clock_period" { incr i; set clock_period [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Resolve the selected cv32e40p checkout. Both checkouts are separate
# submodules so switching the parent repository branch is no longer required
# to compare baseline vs. modified RTL.
if { $core_dir eq "" } {
  switch -- $experiment {
    "baseline" { set core_dir [file join $origin_dir "cv32e40p_baseline"] }
    "no-mul-forwarding" { set core_dir [file join $origin_dir "cv32e40p_no_mul_forwarding"] }
    default {
      puts "ERROR: Unknown experiment '$experiment'. Use --core_dir for a custom checkout."
      return 1
    }
  }
}
if { [file pathtype $core_dir] eq "relative" } {
  set core_dir [file join $origin_dir $core_dir]
}
set core_dir [file normalize $core_dir]

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/"]"

# Check for paths and files needed for project creation
set validate_required 0
if { $validate_required } {
  if { [checkRequiredFiles $origin_dir] } {
    puts "Tcl file $script_file is valid. All files required for project creation is accesable. "
  } else {
    puts "Tcl file $script_file is not valid. Not all files required for project creation is accesable. "
    return
  }
}

if { $user_build_dir eq "" } {
  set safe_experiment [string map {"/" "_" " " "_"} $experiment]
  set build_dir [file join $origin_dir "build" "vivado-$safe_experiment"]
} else {
  if { [file pathtype $user_build_dir] eq "relative" } {
    set user_build_dir [file join $origin_dir $user_build_dir]
  }
  set build_dir [file normalize $user_build_dir]
}
file mkdir $build_dir

if { $clock_period eq "" } {
  switch -- $experiment {
    "no-mul-forwarding" { set clock_period "10.000" }
    default { set clock_period "15.000" }
  }
}

puts "========================================"
puts "cv32e40p ZedBoard project generation"
puts "========================================"
puts "origin_dir  = $origin_dir"
puts "experiment  = $experiment"
puts "core_dir    = $core_dir"
puts "build_dir   = $build_dir"
puts "project     = ${_xil_proj_name_}"
puts "clk_i period= $clock_period ns"
puts "========================================"

# Create project
create_project ${_xil_proj_name_} $build_dir -part xc7z020clg484-1 -force

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [current_project]
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "enable_resource_estimation" -value "0" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "part" -value "xc7z020clg484-1" -objects $obj
set_property -name "revised_directory_structure" -value "1" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "sim_compile_state" -value "1" -objects $obj
set_property -name "webtalk.xsim_launch_sim" -value "1" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Add local files from the original project (-no_copy_sources specified)
set files [list \
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/clk/rtl/gated_clk_cell.v" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_ctrl.v" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_ff1.v" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_pack_single.v" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_prepare.v" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_round_single.v" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_special.v" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_srt_single.v" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_top.v" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_dp.v" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_frbus.v" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_src_type.v" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/cf_math_pkg.sv" ]\
 [file normalize "${core_dir}/rtl/cv32e40p_aligner.sv" ]\
 [file normalize "${core_dir}/rtl/include/cv32e40p_pkg.sv" ]\
 [file normalize "${core_dir}/rtl/cv32e40p_alu.sv" ]\
 [file normalize "${core_dir}/rtl/cv32e40p_alu_div.sv" ]\
 [file normalize "${core_dir}/rtl/include/cv32e40p_apu_core_pkg.sv" ]\
 [file normalize "${core_dir}/rtl/cv32e40p_apu_disp.sv" ]\
 [file normalize "${origin_dir}/zedboard-wrapper/cv32e40p_clock_gate.sv" ]\
 [file normalize "${core_dir}/rtl/cv32e40p_compressed_decoder.sv" ]\
 [file normalize "${core_dir}/rtl/cv32e40p_controller.sv" ]\
 [file normalize "${core_dir}/rtl/cv32e40p_core.sv" ]\
 [file normalize "${core_dir}/rtl/cv32e40p_cs_registers.sv" ]\
 [file normalize "${core_dir}/rtl/include/cv32e40p_fpu_pkg.sv" ]\
 [file normalize "${core_dir}/rtl/cv32e40p_decoder.sv" ]\
 [file normalize "${core_dir}/rtl/cv32e40p_ex_stage.sv" ]\
 [file normalize "${core_dir}/rtl/cv32e40p_ff_one.sv" ]\
 [file normalize "${core_dir}/rtl/cv32e40p_fifo.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_fpnew/src/fpnew_pkg.sv" ]\
 [file normalize "${core_dir}/rtl/cv32e40p_fp_wrapper.sv" ]\
 [file normalize "${core_dir}/rtl/cv32e40p_hwloop_regs.sv" ]\
 [file normalize "${core_dir}/rtl/cv32e40p_id_stage.sv" ]\
 [file normalize "${core_dir}/rtl/cv32e40p_if_stage.sv" ]\
 [file normalize "${core_dir}/rtl/cv32e40p_int_controller.sv" ]\
 [file normalize "${core_dir}/rtl/cv32e40p_load_store_unit.sv" ]\
 [file normalize "${core_dir}/rtl/cv32e40p_mult.sv" ]\
 [file normalize "${core_dir}/rtl/cv32e40p_obi_interface.sv" ]\
 [file normalize "${core_dir}/rtl/cv32e40p_popcnt.sv" ]\
 [file normalize "${core_dir}/rtl/cv32e40p_prefetch_buffer.sv" ]\
 [file normalize "${core_dir}/rtl/cv32e40p_prefetch_controller.sv" ]\
 [file normalize "${core_dir}/rtl/cv32e40p_sleep_unit.sv" ]\
 [file normalize "${core_dir}/rtl/cv32e40p_top.sv" ]\
 [file normalize "${origin_dir}/zedboard-wrapper/dmem_bram.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/include/common_cells/registers.svh" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_fpnew/src/fpnew_cast_multi.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_fpnew/src/fpnew_classifier.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_fpnew/src/fpnew_divsqrt_multi.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_fpnew/src/fpnew_divsqrt_th_32.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_fpnew/src/fpnew_fma.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_fpnew/src/fpnew_fma_multi.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_fpnew/src/fpnew_noncomp.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_fpnew/src/fpnew_opgroup_block.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_fpnew/src/fpnew_opgroup_fmt_slice.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_fpnew/src/fpnew_opgroup_multifmt_slice.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_fpnew/src/fpnew_rounding.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_fpnew/src/fpnew_top.sv" ]\
 [file normalize "${origin_dir}/zedboard-wrapper/imem_bram.sv" ]\
 [file normalize "${origin_dir}/zedboard-wrapper/program_imem.mem" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/lzc.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/rr_arb_tree.sv" ]\
 [file normalize "${origin_dir}/zedboard-wrapper/zedboard_cv32e40p_wrapper.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/cb_filter_pkg.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/counter.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/delta_counter.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/sub_per_hash.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/cb_filter.sv" ]\
 [file normalize "${core_dir}/rtl/cv32e40p_register_file_ff.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/addr_decode.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/binary_to_gray.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/cdc_2phase.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/cdc_fifo_2phase.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/cdc_fifo_gray.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/clk_div.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/deprecated/clock_divider.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/deprecated/clock_divider_counter.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/ecc_pkg.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/ecc_decode.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/ecc_encode.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/edge_detect.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/edge_propagator.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/edge_propagator_rx.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/edge_propagator_tx.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/exp_backoff.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/fall_through_register.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/deprecated/fifo_v1.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/deprecated/fifo_v2.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/fifo_v3.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/deprecated/find_first_one.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/deprecated/generic_LFSR_8bit.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/deprecated/generic_fifo.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/deprecated/generic_fifo_adv.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/gray_to_binary.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/id_queue.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/isochronous_spill_register.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/lfsr.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/lfsr_16bit.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/lfsr_8bit.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/max_counter.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/mv_filter.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/onehot_to_bin.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/plru_tree.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/popcount.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/deprecated/prioarbiter.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/deprecated/pulp_sync.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/deprecated/pulp_sync_wedge.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/deprecated/rrarbiter.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/rstgen.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/rstgen_bypass.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/serial_deglitch.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/shift_reg.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/spill_register.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/deprecated/sram.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/stream_arbiter.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/stream_arbiter_flushable.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/stream_delay.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/stream_demux.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/stream_fifo.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/stream_filter.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/stream_fork.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/stream_fork_dynamic.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/stream_join.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/stream_mux.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/stream_omega_net.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/stream_register.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/stream_to_mem.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/stream_xbar.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/sync.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/sync_wedge.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/unread.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/src/stream_intf.sv" ]\
 [file normalize "${core_dir}/rtl/vendor/pulp_platform_common_cells/include/common_cells/assertions.svh" ]\
]
set added_files [add_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "src/cf_math_pkg.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "rtl/cv32e40p_aligner.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "include/cv32e40p_pkg.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "rtl/cv32e40p_alu.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "rtl/cv32e40p_alu_div.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "include/cv32e40p_apu_core_pkg.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "rtl/cv32e40p_apu_disp.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "zedboard-wrapper/cv32e40p_clock_gate.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "rtl/cv32e40p_compressed_decoder.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "rtl/cv32e40p_controller.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "rtl/cv32e40p_core.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "rtl/cv32e40p_cs_registers.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "include/cv32e40p_fpu_pkg.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "rtl/cv32e40p_decoder.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "rtl/cv32e40p_ex_stage.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "rtl/cv32e40p_ff_one.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "rtl/cv32e40p_fifo.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/fpnew_pkg.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "rtl/cv32e40p_fp_wrapper.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "rtl/cv32e40p_hwloop_regs.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "rtl/cv32e40p_id_stage.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "rtl/cv32e40p_if_stage.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "rtl/cv32e40p_int_controller.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "rtl/cv32e40p_load_store_unit.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "rtl/cv32e40p_mult.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "rtl/cv32e40p_obi_interface.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "rtl/cv32e40p_popcnt.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "rtl/cv32e40p_prefetch_buffer.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "rtl/cv32e40p_prefetch_controller.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "rtl/cv32e40p_sleep_unit.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "rtl/cv32e40p_top.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "zedboard-wrapper/dmem_bram.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "common_cells/registers.svh"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "src/fpnew_cast_multi.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/fpnew_classifier.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/fpnew_divsqrt_multi.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/fpnew_divsqrt_th_32.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/fpnew_fma.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/fpnew_fma_multi.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/fpnew_noncomp.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/fpnew_opgroup_block.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/fpnew_opgroup_fmt_slice.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/fpnew_opgroup_multifmt_slice.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/fpnew_rounding.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/fpnew_top.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "zedboard-wrapper/imem_bram.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "zedboard-wrapper/program_imem.mem"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Memory Initialization Files" -objects $file_obj

set file "src/lzc.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/rr_arb_tree.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "zedboard-wrapper/zedboard_cv32e40p_wrapper.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/cb_filter_pkg.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/counter.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/delta_counter.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/sub_per_hash.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/cb_filter.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "rtl/cv32e40p_register_file_ff.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/addr_decode.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/binary_to_gray.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/cdc_2phase.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/cdc_fifo_2phase.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/cdc_fifo_gray.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/clk_div.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "deprecated/clock_divider.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "deprecated/clock_divider_counter.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/ecc_pkg.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/ecc_decode.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/ecc_encode.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/edge_detect.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/edge_propagator.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/edge_propagator_rx.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/edge_propagator_tx.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/exp_backoff.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/fall_through_register.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "deprecated/fifo_v1.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "deprecated/fifo_v2.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/fifo_v3.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "deprecated/find_first_one.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "deprecated/generic_LFSR_8bit.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "deprecated/generic_fifo.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "deprecated/generic_fifo_adv.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/gray_to_binary.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/id_queue.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/isochronous_spill_register.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/lfsr.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/lfsr_16bit.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/lfsr_8bit.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/max_counter.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/mv_filter.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/onehot_to_bin.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/plru_tree.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/popcount.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "deprecated/prioarbiter.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "deprecated/pulp_sync.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "deprecated/pulp_sync_wedge.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "deprecated/rrarbiter.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/rstgen.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/rstgen_bypass.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/serial_deglitch.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/shift_reg.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/spill_register.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "deprecated/sram.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/stream_arbiter.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/stream_arbiter_flushable.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/stream_delay.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/stream_demux.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/stream_fifo.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/stream_filter.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/stream_fork.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/stream_fork_dynamic.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/stream_join.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/stream_mux.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/stream_omega_net.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/stream_register.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/stream_to_mem.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/stream_xbar.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/sync.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/sync_wedge.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/unread.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/stream_intf.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "common_cells/assertions.svh"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj


# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "include_dirs" -value "[file normalize "$core_dir/rtl/include"] [file normalize "$core_dir/rtl/vendor/pulp_platform_common_cells/include"] [file normalize "$core_dir/rtl/vendor/pulp_platform_fpnew/src/common_cells/include"]" -objects $obj
set_property -name "top" -value "zedboard_cv32e40p_wrapper" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties. The baseline keeps
# the board default 15 ns target; the modified experiment uses its own generated
# XDC so its clock target can be swept independently without changing baseline.
set base_constraints_file "[file normalize "$origin_dir/zedboard-wrapper/constraints.xdc"]"
set constraints_file $base_constraints_file
if { $experiment eq "no-mul-forwarding" || $clock_period ne "15.000" } {
  set constraints_file [file normalize [file join $build_dir "constraints-${experiment}-${clock_period}ns.xdc"]]
  set in_fp [open $base_constraints_file r]
  set constraints_text [read $in_fp]
  close $in_fp
  regsub {create_clock -period [0-9.]+ -name clk_i \[get_ports clk_i\]} $constraints_text "create_clock -period $clock_period -name clk_i \[get_ports clk_i\]" constraints_text
  set out_fp [open $constraints_file w]
  puts -nonewline $out_fp $constraints_text
  close $out_fp
}
set file_added [add_files -norecurse -fileset $obj [list $constraints_file]]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list $constraints_file]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "target_part" -value "xc7z020clg484-1" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Add local files from the original project (-no_copy_sources specified)
set files [list \
 [file normalize "${origin_dir}/zedboard-wrapper/tb_zedboard_cv32e40p_wrapper.sv" ]\
]
set added_files [add_files -fileset sim_1 $files]

# Set 'sim_1' fileset file properties for remote files
# None

# Set 'sim_1' fileset file properties for local files
set file "zedboard-wrapper/tb_zedboard_cv32e40p_wrapper.sv"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj


# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "top" -value "tb_zedboard_cv32e40p_wrapper" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Empty (no sources present)

# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]

set idrFlowPropertiesConstraints ""
catch {
 set idrFlowPropertiesConstraints [get_param runs.disableIDRFlowPropertyConstraints]
 set_param runs.disableIDRFlowPropertyConstraints 1
}

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xc7z020clg484-1 -flow {Vivado Synthesis 2022} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2022" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "part" -value "xc7z020clg484-1" -objects $obj
set_property -name "auto_incremental_checkpoint" -value "1" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xc7z020clg484-1 -flow {Vivado Implementation 2022} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2022" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "options.verbose" -value "1" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
set obj [get_runs impl_1]
set_property -name "part" -value "xc7z020clg484-1" -objects $obj
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]
catch {
 if { $idrFlowPropertiesConstraints != {} } {
   set_param runs.disableIDRFlowPropertyConstraints $idrFlowPropertiesConstraints
 }
}

puts "INFO: Project created:${_xil_proj_name_}"
# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets [ list "drc_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets [ list "power_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets [ list "timing_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1